---

- name: Install traceroute
  apt:
    name: traceroute
    update_cache: yes


- name: Remove ifupdown1 and netplan
  apt:
    name: ['ifupdown','ifenslave','netplan.io']
    state: absent

# Add the mpls_iptunnel module
- modprobe:
    name: mpls_iptunnel
    state: present
