---

- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes

#- name: Copy interfaces configuration
#  copy:
#    src: configurations/{{inventory_hostname}}_interfaces.txt
#    dest: /etc/network/interfaces
#    backup: yes
#  notify: reload networking

- name: Sleep for server to disconnect
  pause:
    seconds: 10

- name: reboot
  reboot:
    pre_reboot_delay: 60
